### ISSUE TITLE
Fix request: Request without GET or POST

### ISSUE THREAD

**Issue by akondasif** [AndreasKl/spring-playground#1]
Greetings, 

We are researchers and we are have identified insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of `@RequestMapping" methods without POST or GET` . According to the Common Weakness Enumeration and [JAVA OWASP](https://rules.sonarsource.com/java/tag/owasp/RSPEC-3752), this is a security weakness and needs to be avoided. 

We request for a fix for this issue. Looking forward for your feedback. 

Source: https://github.com/AndreasKl/spring-playground/blob/ab1e84d19c8f12bf49c6e919a9a3eefeb20a802d/AgileCafe/src/net/andreaskluth/controller/PersonController.java#L25

and 

https://github.com/AndreasKl/spring-playground/blob/master/oauth2-with-google/src/main/java/net/andreaskluth/oauth/Application.java

**Comment by AndreasKl** [comment]
This is non production ready test code, not used for anything. Thanks for the hint.
